apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
  labels:
    app: example
spec:
  selector:
    matchLabels:
      name: example-pod
  template:
    metadata:
      labels:
        name: example-pod
        env: devops
    spec:
      containers:
      - name: example-container
        image: nginx
        ports:
        -