apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        env: devops
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: nginx-image
          containerPort: 80