apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        name: mypod
        env: devops
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80