apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: spider4
      labels:
        env: devops
    spec:
      containers:
       - name: nginx
         image: nginx:1.14.2
         env:
          name: hello
          valuesFrom: 
            configMapKeyRef:
              name: myvariable
              key: env
        ports:
          - containerPort: 80
