apiVersion: v1
kind: ReplicationController
metadata:
  name: spider3
spec:
  replicas: 3
  selector:
    app: spider3
  template:
    metadata:
      name: spider2
      labels:
        name: myapp
    spec:
     containers:
       - name: spider2
       image: nginx
       ports:
      - containerPort: 80


