apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: myreplicationcontroller
spec:
  replicas: 3
  selector:
    app: spider3
  template:
    metadata:
      name: spider3
      labels:
        name: myreplicationcontroller
    spec:
      containers:
        - name: spider3
          image: nginx
          ports:
            - containerPort: 80

