apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-ss
  template:
    metadata:
      name: mypod-ss
      labels:
        app: myapp-ss
        env: devops
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 80
          name: db
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  
