apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-ss
  template:
    metadata:
      name: mypod-ss
      labels:
        app: myapp-ss
        env: devops
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - name: db
          containerPort: 80
        env: 
        - name: MARIADB_ROOT_PASSWORD
          value: 
          
       
